### ISSUE TITLE
Amnoah

### ISSUE THREAD

**Issue by Diamondy01** [amnoah/overcomplicated-pong#1]
please unarchive the benchmark repository kindly :)

**Comment by amnoah** [comment]
This is NOT an acceptable way of asking for this sort of thing. This project is completely unrelated with Host Benchmark and you should not be opening issues on it to ask for things for Host Benchmark.

I do not have any plans of maintaining Host Benchmark, and I had no plans of that prior to archiving it. I have not touched the project for 8 months and don't plan on changing that - but you are more than welcome to maintain it. It is open source for a reason.
